services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 10s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - "./db/db_scripts/:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=db_todo
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
  dataservice:
    image: td1011/stl-data-service:1.0.0-alpha
    ports:
      - 8080:8000
    links:
      - "db:database"
    environment:
      - IS_PRODUCTION=true
      - USE_WSGI=true
      - MYSQLDB_HOST=database
      - MYSQLDB_DB=db_todo
      - MYSQLDB_USER=todo_user
      - MYSQLDB_PASSWORD=<changeme>
  frontend: 
    image: td1011/stl-frontend:1.0.0-demo
    container_name: frontend
    ports:
      - 8000:80
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos
secrets:
  db-password:
    file: db_password.txt
